name: Package AIX Studio Desktop
on:
  push:
    branches:
      - master
jobs:
  publishdmg:
    name: Publish DMG
    runs-on: macOS-latest
    if: "contains(toJSON(github.event.commits.*.message), '[package]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install and publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install macos-alias
          npm install nan
          yarn
          yarn build
          yarn package:all
  publishexe:
    name: Publish EXE
    runs-on: windows-latest
    if: "contains(toJSON(github.event.commits.*.message), '[package]')"	
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install and publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn
          yarn build
          yarn package:all
